version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: lumio-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: lumio
      POSTGRES_PASSWORD: lumio_secret
      POSTGRES_DB: lumio_db
    ports:
      - "5434:5432"
    volumes:
      - lumio_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lumio -d lumio_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  lumio_pgdata:
